name: Publish Docker image to GitHub Package Registry
on: push
jobs:
  build:
    runs-on: ubuntu-latest 
    if: github.ref == 'refs/heads/master' 
    
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v2

     #This Action Emits 2 Variables, IMAGE_SHA_NAME and IMAGE_URL 
     #which you can reference in subsequent steps
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'lindat-billing'
        TAG: 'latest'
        DOCKERFILE_PATH: 'Docker/frontend/Dockerfile'
        BUILD_CONTEXT: './'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
